 
      
app:
  jwtExpirationInMs:  1800000 # 604800000 = 7 * 24 * 3600 * 1000
  jwtSecret: JWTSuperSecretKey@PhotoSaver
   
server:
  compression:
    enabled: true
  port: 5002
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service2?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: dbuser
    password: DBPassw0rd!
    initialization-mode: never
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    #time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 
      show_sql: false
      format_sql: false
        
